### ISSUE TITLE
Communities smaller than 50 users

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-app#19]
JoatU admins will control the creation of communities.

When a JoatU user joins a community with less than 50 people, I would like for them to receive a notification that alerts them of how many more users are needed to unlock their community.

"47 more users needed to unlock the search function in this community."

Unlocked communities give individuals living within this area the capabilities to search for other users within that same community.  Individuals living in communities with greater than 50 users can search beyond their own community and can contact & trade with members in communities with less than 50 users.

Advantages: Will provide a lot of offers for the community once available.  Will create incentive to get your neighbors involved.

Disadvantage: Does not allow early adopters to coordinate to find the rest of the people to join their communities.

Possible Workaround: Forum (external to JoatU) for each community.

**Comment by undergroundwebdesigns** [comment]
This does not seem like a good idea to me at all, specifically for the reason you posted as a disadvantage. We are building a network site, that is, it becomes more useful the more people are on it _and are connected through it_. Limiting searches to only those communities with 50 or more members will make the site practically useless to all communities less than 50 members (which is, right now, everybody), and which won't incentivise them to use it at all.

**Comment by joatu** [comment]
It's critical to create incentive for rarer trades to become a part of the site.  What if we required ~50 members to join within 2km of center pod before launching, and once it has launched in the site, it's extended 25km in each direction from the center and everyone can join for that pod/city.  Once we obtain ~50 members that are close to another area, we launch another community, transferring the users over to the new community and allowing them the possibility to search all local communities, or just their own close-by 2km micro community.

**Comment by damienjoatu** [comment]
I have to agree with Alex on this.

I think the radius for a community should be flexible. There's 5 users around Tulsa, OK? maybe radius should be 50km. There's 100 users on the Plateau, make it 2km. We could start with a big radius (say: city) and split it when the number of users is sufficient (say: neighborhood) 

Even better: Montreal is a community and the Plateau is also a community. Users can belong to multiple communities (one where they live, one where they work, one at their parents') I think the more flexibility, the fewer restrictions, the better.

The real added value would be to keep this flexibility and give users the _choice_ in the search radius (if you have a car you can go much farther than if you don't)
Kijiji, for example, allows to define a radius for searching around a given point .

**Comment by undergroundwebdesigns** [comment]
At this point, I'm questioning whether we should even have the concept of communities, at least to start. I know that seems like a big change, but hear me out.

@joatu it seems to me like you're worried about people joining, doing a search, not seeing anything (or only seeing items that are far away from them) and getting discouraged. That's a valid concern, and it's a tricky problem to solve. Social networks are, by nature, not very useful till a lot of people are using them. I do think there are better solutions than crippling search till a certain number of people join though. If we're thinking of doing something like that, then I would recommend that we only allow people to _register_ if they're within a certain area (maybe Montreal), and inform other people that we're "not yet launched in their city". It's frustrating to people to go through the hassle of signing up only to find that they can't really use the site (for whatever reason), so I'd say better to not have them sign up at all if it's not going to be useful to them. Instead, we could have a form that collects email addresses (and maybe city name) to put people on a "waiting list" so we can let them know when we _do_ open up JoatU to their city.

Then, (assuming we launch in Montreal first), we allow anyone in Montreal to register. What if, initially, we just collect some location information from people (postal / zip code), and we don't assign people to any sort of community at all. Search is left extremely basic, so it just shows everything in the system, though we could set it up to prioritize matches that are located close to the searcher. At this point the system is at least _basically_ useful to the people who have registered to the site (people in Montreal).

At this point, we keep track of where people are registering, and as we see groups forming (e.g., lots of users registering on the Plateau) we can create a community for them. Waiting like this helps us prioritize features (we can move forward with getting people signed up and using the site even while we're still figuring out exactly what we want communities to do) and gives us time to build the community specific features. @joatu during this time (as people are registering, but not yet a part of a community) we can advertise the upcoming community feature, and possibly even do something like you suggested where we let them know how many more people need to join before a community in their area will be created.

Then, as for communities themselves... what if rather than _just_ a radius, we used a shape on a map? It's not that much more difficult to do, and (I think) will be much more useful and realistic, allowing us to shape communities to existing neighbourhoods rather than just defining them as a circle around a given point. We can also do some "smart" searches, such as:
- automatically including search results from nearby communities if there are few matches within your "home" community
- allow people to specify approximately how far they'd be willing to travel for something (for a given search), and then running the search for all communities within that distance.
- Let people choose to search in just a few specific communities, or exclude specific communities.

My point being, we're not at all limited to just radius search, so let's try to think outside the box on what will make communities the most useful to people. From my perspective, communities are one of the key features of JoatU, and are something we want to get right, not something we want to rush into. Let's not worry so much about what's quick or easy, and let's focus on how we want communities to work in the long run... what benefits we want them to provide. Then we can work backwards from that to an actual implementation.

**Comment by joatu** [comment]
I actually really like the way you're imagining it @undergroundwebdesigns 

I think you're right.  As long as we make sure to be collecting emails+locations from users not located around a JoatU city in a way that wouldn't push them away, I think we'll be alright.  I like the idea of needing X number within the city to launch, and so to auto-send them an email letting them know that they need Y more users before launching and informing them of ways they can get people in their neighborhood to join (flyers they can handout, pages they can share, etc).

The shape thing too, overlapping shapes as well, selecting a 'home', and 'extended' neighborhoods (as discussed a long time back).

I'm really loving how these ideas are evolving.  Great thinking & work!

**Comment by undergroundwebdesigns** [comment]
Ya, I'd really like to brainstorm more about what we want these "communities" to be. Obviously they'll play a part in search, probably acting as predefined "areas" which can be combined with other geographical filters, but what else are we going to do with these communities? One of CouchSurfing's new-er features (it's a few years old now) is "place pages", which are usually city level pages and show events happening in the city, there's a message board people can chat on, pictures, that sort of thing. CouchSurfing's attempt is actually pretty shitty, but the idea is good, I think. Especially if we were working on an even smaller level, neighbourhoods and small self-selected communities, having some sort of hub page not only showcasing recent offers and requests, but also providing a sort of virtual bulletin board and community space... that could be really cool no? What else could we do with them?

**Comment by joatu** [comment]
Yes, I definitely like that idea, and adding in http://www.loomio.org features as well (over time), but more to be discussed about that as it develops.  I like the idea of a Place Page for community events to be auto-posted to.  And people can receive notifications of new events on the pages they select.

Something else I wanted was the ability to overlap postings.  For example, The Plateau is within Montreal, so I'd want my event posting to show that it is both on the Plateau page and the Montreal page, even though I just posted it in the smaller area.  And larger than that, on the Quebec, Canada, and Global pages too.  I suppose that gets a bit crazy, so maybe not exactly for everything, but I'm imagining that we can use loomio for community decisions, but I would later want to expand that to determine policies for communities/cities/provinces/countries/world.  Just some thoughts to put onto the backburner.

A simple (free) events page for each neighborhood (or city to start and later for the neighborhood) would be good enough for the time being.

**Comment by damienjoatu** [comment]
I think these are all good directions:
- radius Vs neighborhood:  I agree that the "radius" is not necessarily the best solution - can we make that work with pre-existing neighborhoods in google maps?
- hub page: double-YES. Having some "this is happening in your community" page as default when you log on would be amazing and possibly a key part of the JoatU user experience. This could cover new users / offers, community events, community votes (loomio)

**Comment by undergroundwebdesigns** [comment]
@damienjoatu yes, we can potentially make use of the pre-existing neighbourhoods in g-maps, as well as custom defined shapes, etc. The geographical tools we have access too are really quite powerful.

@joatu the over-lap post thing can work, though I'd question if it's worth going up any higher than city level. At that point you already have to aggregate / sort through a lot of information. I personally think JoatU should focus small first, on connecting neighbourhoods and communities and encouraging collaboration amongst them. When that is going well, then we can think about taking the generated information and seeing what's useful at a more macro level. Focusing too early on "big picture" stuff, even city level stuff, will be both distracting right now, and not really that useful for anyone, as you need a LOT of data to make an aggregate at that level useful.

**Comment by joatu** [comment]
I agree with you.  For city-wide stuff or larger, it was more in regards to policy-making and utilizing loomio than for making direct trades or exchanges...It still remains far enough into the future though that it isn't a priority by any stretch of the imagination.

**Comment by undergroundwebdesigns** [comment]
I'm going to close this, as I think the discussion has been productive, and I've opened issue #40 which takes into account the decisions made here in regards to a new, simpler signup process.
