### ISSUE TITLE
development-environment

### ISSUE THREAD

**Issue by TedEwanchyna** [joatuapp/joatu-app#32]
I have been looking at your code from github but I would like to install it locally so that I can play with the system. I started on my ubuntu 12.04 but could not get past complaints for preset environment variables. So I got another machine and installed ubuntu 14.04 and found I pretty much have the same problem.

I have been adding the following to my .bashrc file:

export SECRET_KEY_BASE='485f9620d248bb568241616673ae66cb3862c8c2778ade2339e7b7f3e39bc5995dfeaa3f14423d0ca4ddbc04a97f826f82ae7f5641e2217d677c1ca9d7fd22f7'
export UNICORN_APP_PATH='/home/ted/test/joatu-app'
export UNICORN_COUNT=1
export API_SUBDOMAIN=''
export CORS_ORIGINS=''
export DEVISE_PEPPER=''
export DEVISE_MAILER_SENDER=''
export DEVISE_SECRET=''
export SMTP_PASSWORD=''
export APP_HOST=localhost

If i run rails server (default server) I get a picture as a home page on port 8080.
I can't seem to get anything if I start the unicorn server. So at this stage I am basically trying to hack it to gt it to run. Any suggestions?

I may take another crack at it using docker. Last time I checked the readme had instructions for docker but they have since been removed. Should I bother with docker?

**Comment by undergroundwebdesigns** [comment]
Hi Ted,

Thanks to this, I realized I was missing a step in the readme. There's a .env.sample file in the repository, and if you copy this to be named ".env" (which is gitignored) foreman will read the env variables from that file on startup. The .env.sample file has all the required environment variables within it, as well as default values for many which can be left unchanged.

As per our email discussion, you're right, the unicorn config file wasn't configured to listen on 8080. I've since fixed it :)
